name: Update Products JSON

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    # ✅ دسترسی نوشتن برای توکن پیش‌فرض
    permissions:
      contents: write

    steps:
      # ✅ توکن شخصی رو حذف کن
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Fetch data from GAS
        run: |
          curl -o products.json "https://script.google.com/macros/s/AKfycbwz80fmQyI8mJxEvtalpW84o1qvETQoO75hHb9yOTH4gYP81im6QAXpfXgPJTmHsyM/exec?action=getFullData"
      
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add products.json
          git diff-index --quiet HEAD || (git commit -m "🤖 Auto-update data" && git push)
